spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost/spring_cloud?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
env:
  test
girl:
  name: 丽丽
  age: 20
